import {useEffect,useState} from 'react';
import {Play,Pause,ChevronLeft,ChevronRight,X} from 'lucide-react';
export const STEPS=[
 ['Mission Control','00:00–00:20','The problem','Land records disagree across agencies. BhoomiSync turns fragmented sources into explainable spatial evidence.'],
 ['City Atlas','00:20–00:45','Start with real geography','Rotate the 3D map. Select a ward, switch to hotspots and show the four clusters. Real boundaries; calculated proxy clearly labeled.'],
 ['Sources','00:45–01:05','Bring six sources together','Show the source registry, mixed coordinate systems and provenance. The land-record demonstration is synthetic.'],
 ['Harmonize','01:05–01:30','Run the engine','Click Run Harmonization. Explain reprojection, topology repair, candidate matching and confidence scoring.'],
 ['Map Review','01:30–02:05','Investigate a disagreement','Find BS-P-00002. Toggle Source comparison. Inspect the measured boundary deviation and linked evidence.'],
 ['Survey Lab','02:05–02:35','Check the ground','Switch imagery to Vegetation zones, enable canopy candidates and show partial imagery coverage. RGB is not NDVI.'],
 ['Case Desk','02:35–03:20','Make the decision traceable','Select a review case, save field-verification instructions, then show the Audit timeline. Attach and verify a file if time allows.'],
 ['Field Ops','03:20–03:45','Close the loop','Create a geofence and test inside/outside transitions, or move a field assignment across the board.'],
 ['Exports','03:45–04:00','Deliver interoperable results','Download the harmonized GeoJSON and explain human-reviewed, traceable land-record management.']
];
export default function DemoGuide({onNavigate,onClose}){const [step,setStep]=useState(0),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(false),[compact,setCompact]=useState(false);useEffect(()=>{onNavigate(STEPS[step][0]);},[step]);useEffect(()=>{const handler=e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.altKey&&e.key==='ArrowRight'){e.preventDefault();setStep(s=>Math.min(STEPS.length-1,s+1));}if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();setStep(s=>Math.max(0,s-1));}if(e.key==='Escape')onClose();};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[onClose]);useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id);},[running]);return <div className={`demo-guide ${compact?'compact':''}`}><div className="demo-guide-clock"><span>DEMO DIRECTOR</span><strong>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong><button aria-label={running?'Pause demo timer':'Start demo timer'} onClick={()=>setRunning(!running)}>{running?<Pause size={13}/>:<Play size={13}/>}</button></div><div className="demo-guide-copy"><span>SCENE {step+1}/{STEPS.length} · {STEPS[step][1]}</span><strong>{STEPS[step][2]}</strong>{!compact&&<p>{STEPS[step][3]}</p>}</div><div className="demo-guide-controls"><button aria-label="Previous demo scene" disabled={!step} onClick={()=>setStep(s=>s-1)}><ChevronLeft size={18}/></button><button className="next-scene" disabled={step===STEPS.length-1} onClick={()=>setStep(s=>s+1)}>Next scene<ChevronRight size={17}/></button><button onClick={()=>setCompact(!compact)}>{compact?'Expand':'Minimize'}</button><button aria-label="Close demo director" onClick={onClose}><X size={17}/></button></div></div>;}
