import {useState} from 'react';
import {ChartNoAxesCombined,Database,Workflow,Map,ListFilter,Download,Layers3,PanelLeftClose,PanelLeftOpen,Globe2,ScanLine,CloudSun,ShieldCheck,Radio,Command,Play,UserRound} from 'lucide-react';
const groups=[['WORKSPACE',[['Mission Control',Command],['City Atlas',Globe2]]],['LAND RECORDS',[['Sources',Database],['Harmonize',Workflow],['Map Review',Map],['Conflicts',ListFilter]]],['INTELLIGENCE',[['Survey Lab',ScanLine],['Environment',CloudSun],['Case Desk',ShieldCheck],['Field Ops',Radio]]],['DELIVER',[['Overview',ChartNoAxesCombined],['Exports',Download]]]];
const displayNames={'Survey Lab':'Imagery Intelligence','Environment':'Context Intelligence','Case Desk':'Review Desk'};
export default function Sidebar({page,onNavigate,collapsed,setCollapsed,role,onRole,onDemo}) {
 const [language,setLanguage]=useState('en');
 const tamil={'Mission Control':'முகப்பு','City Atlas':'நகர வரைபடம்','Sources':'தரவு மூலங்கள்','Harmonize':'ஒருங்கிணைப்பு','Map Review':'வரைபட ஆய்வு','Conflicts':'முரண்பாடுகள்','Survey Lab':'நில ஆய்வகம்','Environment':'சுற்றுச்சூழல்','Case Desk':'பதிவு ஆய்வு','Field Ops':'களப்பணிகள்','Overview':'மேலோட்டம்','Exports':'ஏற்றுமதி'};
 return <nav className={'sidebar '+(collapsed?'is-collapsed':'')} aria-label="Main navigation"><div className="brand"><div className="brand-emblem"><Layers3/></div><div><strong>BhoomiSync<span className="brand-period">.</span></strong><small>LAND INTELLIGENCE STUDIO</small></div></div><div className="navigation-group">{groups.map(([name,items])=><div className="nav-section" key={name}><span className="nav-group-label">{name}</span>{items.map(([label,Icon])=>{const display=displayNames[label]||label;return <button key={label} title={display} aria-label={display} aria-current={page===label?'page':undefined} className={'nav-item '+(page===label?'is-active':'')} onClick={()=>onNavigate(label)}><Icon/><span>{language==='ta'?tamil[label]:display}</span>{page===label&&<i className="nav-active-dot"/>}</button>})}</div>)}</div><div className="sidebar-bottom"><button className="sidebar-demo" title="Open demo director" onClick={onDemo}><Play size={13}/><span>Demo director</span><small>4 MIN</small></button><label className="sidebar-persona" title="Local demo persona"><UserRound size={14}/><select aria-label="Workspace persona" value={role} onChange={e=>onRole(e.target.value)}><option value="officer">Officer / editor</option><option value="analyst">Analyst / editor</option><option value="viewer">Landowner / viewer</option></select></label><div className="navigation-language"><span>Navigation</span><button aria-label="English navigation" className={language==='en'?'active':''} onClick={()=>setLanguage('en')}>EN</button><button aria-label="Tamil navigation" className={language==='ta'?'active':''} onClick={()=>setLanguage('ta')}>TA</button></div><div className="environment"><span className="environment-dot"/><div>SIH26013<small>Local prototype / v2.0</small></div></div><button className="sidebar-toggle" aria-label={collapsed?'Expand navigation':'Collapse navigation'} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}<span>Collapse navigation</span></button></div></nav>;
}
