import {useState} from 'react';
import {ChevronDown, ChevronUp, FileSearch, ExternalLink} from 'lucide-react';
import StatusIndicator from '../../components/StatusIndicator';
import {formatNumber,metres,percent,pilotRecordLabel,sourceName,titleCase} from '../../api/presentation';

function Fields({rows}) {return <dl className="inspector-fields">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'—'}</dd></div>)}</dl>;}
function Section({title,count,children}) {return <section className="inspector-section"><h3>{title}{count!=null&&<span>{count}</span>}</h3>{children}</section>;}
export default function ParcelInspector({parcel,onFocus}) {
  const [tab,setTab]=useState('Evidence'),[expanded,setExpanded]=useState(false);
  if(!parcel)return <aside className="parcel-inspector"><div className="inspector-empty"><FileSearch/><h2>No parcel selected</h2><p>Click a parcel on the map or search its ID in the toolbar.</p></div></aside>;
  const p=parcel,m=p.metrics;
  return <aside className="parcel-inspector" aria-label="Parcel inspector"><div className="inspector-header"><div className="inspector-heading"><div><span className="panel-kicker">Parcel inspector</span><h2>{p.parcel_id}</h2></div><button className="icon-button" aria-label="Focus inspected parcel" title="Focus inspected parcel" onClick={onFocus}><ExternalLink/></button></div><div className="inspector-status-line"><StatusIndicator status={p.status}/><span className="confidence-value">{percent(p.confidence)}<small>Confidence</small></span></div><div className="thin-confidence" style={{'--confidence':`${p.confidence}%`,'--status-color':p.status==='MATCHED'?'var(--matched)':p.status==='CONFLICT'?'var(--conflict)':'var(--review)'}}><span/></div><div className="inspector-context"><span>Survey <strong>{p.survey_number||'—'}</strong></span><span>Sources <strong>{p.source_count}</strong></span></div><div className="decision-line">{p.auto_harmonized?'Auto harmonized · cadastral retained':'Survey verification required'}</div></div>
    <div className="inspector-tabs" role="tablist" aria-label="Inspector sections">{['Evidence','Records','Provenance'].map(name=><button role="tab" aria-selected={tab===name} className={tab===name?'is-active':''} key={name} onClick={()=>setTab(name)}>{name}</button>)}</div>
    <div className="inspector-scroll" role="tabpanel">
    {tab==='Evidence'&&<><Section title="Match evidence"><Fields rows={[
      ['Polygon IoU',formatNumber(m.iou,3)],['Centroid shift',metres(m.centroid_distance_m)],['Boundary distance',metres(m.boundary_distance_m)],
      ['Area similarity',m.area_similarity==null?'—':percent(m.area_similarity*100)],['Attribute similarity',m.attribute_similarity==null?'—':percent(m.attribute_similarity*100)],['GNSS deviation',metres(m.gnss_deviation_m)],['Topology',titleCase(p.topology)],
    ]}/></Section><Section title="Source records" count={p.source_count}><div className="source-record-list">{Object.entries(p.source_ids).map(([id,value])=><div key={id}><span className={`source-dot source-${id}`}/><span>{sourceName(id)}</span><code title={value}>{value}</code></div>)}</div></Section><Section title="Conflicts" count={p.conflicts.length}>{p.conflicts.length?p.conflicts.map(issue=><div className={`inspector-issue issue-${issue.severity}`} key={issue.id}><div><strong>{titleCase(issue.type)}</strong><StatusIndicator status={issue.severity}/></div><p>{issue.description}</p><small>{issue.recommended_action}</small></div>):<p className="muted compact">No conflicts detected.</p>}</Section><Section title="Change detection" count={p.changes.length}>{p.changes.length?p.changes.map(change=><div className="inspector-change" key={change.id}><strong>{titleCase(change.type)}</strong><p>{change.description}</p></div>):<p className="muted compact">No detected differences in available observations.</p>}</Section><Section title="Explanation"><ul className="evidence-list">{p.explanation.map((text,i)=><li key={i}>{text}</li>)}</ul><div className="recommendation"><strong>Recommendation</strong><p>{p.recommendation}</p></div></Section></>}
    {tab==='Records'&&<><Section title="Canonical record"><Fields rows={[
      ['Parcel ID',p.parcel_id],['Survey number',p.survey_number],['Municipal ID',p.municipal_property_id],['Revenue ID',p.revenue_record_id],['Pilot record',pilotRecordLabel(p.owner_name)],['Land use',p.land_use],['Calculated area',`${formatNumber(p.area_sqm,2)} m²`],['Recorded area',p.recorded_area_sqm==null?'—':`${formatNumber(p.recorded_area_sqm,2)} m²`],['Area disagreement',percent(m.recorded_area_difference_percent)],['Perimeter',`${formatNumber(p.perimeter_m,2)} m`],
    ]}/></Section>{Object.entries(p.metadata?.source_properties||{}).map(([source,properties])=><Section key={source} title={sourceName(source)}><Fields rows={Object.entries(properties).filter(([k])=>k!=='data_label').map(([k,v])=>[titleCase(k),k==='owner'||k==='holder'?pilotRecordLabel(v):String(v??'—')])}/></Section>)}</>}
    {tab==='Provenance'&&<><Section title="Processing provenance"><Fields rows={[
      ['Analysis CRS',p.metadata?.analysis_crs],['Master geometry',titleCase(p.metadata?.master_geometry_policy)],['Municipal CRS',p.metadata?.municipal_original_crs],['Geometry repairs',p.metadata?.repair_operations?.length||0],['Automatic decision',p.auto_harmonized?'Accepted':'Requires review'],
    ]}/></Section><Section title="Candidate evidence">{p.metadata?.candidate_scores?.map(c=><div className="candidate-row" key={c.source_id}><code>{c.source_id}</code><span>{percent(c.score,2)}</span></div>)}</Section><Section title="Repair operations">{p.metadata?.repair_operations?.length?<pre>{JSON.stringify(p.metadata.repair_operations,null,2)}</pre>:<p className="muted compact">No repairs recorded.</p>}</Section><Section title="Original observations"><button className="button quiet disclosure" onClick={()=>setExpanded(!expanded)}>{expanded?<ChevronUp/>:<ChevronDown/>}{expanded?'Hide':'Show'} raw provenance</button>{expanded&&<pre>{JSON.stringify(p.metadata,null,2)}</pre>}</Section></>}
    </div><div className="inspector-foot">Evidence score · not a legal determination</div>
  </aside>;
}
