import {useRef,useState} from 'react';
import {Search,ArrowUpRight,ShieldCheck,FileText,Upload,Download,Check,Clock,History,Trash2,FolderCheck} from 'lucide-react';
import {Heading,useResource,Loading,Kicker,SourceNote,mutation,LinkAction,num} from '../features/intelligence/shared';
import {request,API} from '../api/client';
export default function CaseDesk({workspace,onInspect,role='officer'}){
 const reviews=useResource('/reviews'),docs=useResource('/documents'),audit=useResource('/audit');
 const [tab,setTab]=useState('reviews'),[query,setQuery]=useState(''),[selected,setSelected]=useState(workspace.parcels?.find(p=>p.parcel_id===workspace.selected&&p.review_required)?.parcel_id||workspace.parcels?.find(p=>p.review_required)?.parcel_id||''),[status,setStatus]=useState('field_check'),[note,setNote]=useState(''),[feedback,setFeedback]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[verified,setVerified]=useState({});const file=useRef();
 const parcels=workspace.parcels||[],p=parcels.find(p=>p.parcel_id===selected)||parcels.find(p=>p.review_required)||parcels[0];
 const history=reviews.data?.filter(r=>r.run_id===workspace.summary?.run_id)||[];
 const rows=parcels.filter(p=>p.review_required||history.some(r=>r.parcel_id===p.parcel_id)).filter(p=>`${p.parcel_id} ${p.owner_name}`.toLowerCase().includes(query.toLowerCase()));
 async function act(fn,message){setBusy(true);setError('');setFeedback('');try{await fn();await Promise.all([reviews.refresh(),docs.refresh(),audit.refresh()]);setFeedback(message);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function upload(e){const f=e.target.files[0];if(!f)return;await act(async()=>{const form=new FormData();form.append('file',f);form.append('parcel_id',p?.parcel_id||'workspace');await request('/documents',{method:'POST',headers:{'X-Workspace-Role':role},body:form});},'Evidence uploaded and SHA-256 recorded.');e.target.value='';}
 return <div className="studio-document"><Heading eyebrow="HUMAN-IN-THE-LOOP / RECORDS & ACCOUNTABILITY" title="Evidence deserves a decision." description="Assign a review outcome, preserve the reasoning and verify supporting files."><LinkAction href="/evidence-bundle">Export evidence bundle</LinkAction></Heading><div className="case-summary"><div><strong>{rows.length}</strong><span>cases in the review queue</span></div><div><strong>{history.length}</strong><span>decisions saved for this run</span></div><div><strong>{docs.data?.length||0}</strong><span>evidence documents</span></div><div><ShieldCheck/><span>Local {role} persona<br/>Persistent SQLite workspace</span></div></div><div className="environment-nav"><div className="s-segments">{[['reviews','Case review'],['documents','Evidence vault'],['audit','Audit timeline']].map(([id,t])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{t}</button>)}</div><span className="s-small">Reviews annotate the result; source geometry stays traceable.</span></div>{feedback&&<div className="s-success" role="status"><Check size={15}/>{feedback}</div>}{error&&<div className="s-error" role="alert">{error}</div>}
 {tab==='reviews'&&<div className="case-layout"><section className="s-panel case-queue"><label className="s-search"><Search size={14}/><input aria-label="Search case queue" placeholder="Find a review parcel…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{rows.length?rows.map(row=>{const review=history.find(r=>r.parcel_id===row.parcel_id);return <button key={row.parcel_id} className={`case-row ${p?.parcel_id===row.parcel_id?'active':''}`} onClick={()=>{setSelected(row.parcel_id);setNote('');setFeedback('');}}><div><strong>{row.parcel_id}</strong><small>{row.owner_name}</small></div><span>{review?review.status.replaceAll('_',' '):`${row.confidence}% confidence`}</span><i className={review?'reviewed':''}/></button>;}):<p className="s-muted">No review cases. Run harmonization or adjust your search.</p>}</section><section className="s-panel case-detail">{p?<><div className="panel-heading"><div><Kicker>PARCEL REVIEW / DEMO RECORD</Kicker><h2>{p.parcel_id}</h2></div><button className="s-button" onClick={()=>onInspect(p.parcel_id)}>Inspect on map<ArrowUpRight size={14}/></button></div><div className="case-evidence-values"><div><span>Evidence confidence</span><strong>{p.confidence}%</strong></div><div><span>Survey area</span><strong>{num(p.area_sqm)}<small> m²</small></strong></div><div><span>Linked sources</span><strong>{p.source_count}</strong></div></div><h3>Pipeline evidence</h3><ul className="evidence-list">{p.explanation?.map(e=><li key={e}><Check size={13}/>{e}</li>)}</ul><p className="case-recommendation">{p.recommendation}</p>{history.find(r=>r.parcel_id===p.parcel_id)&&<div className="saved-review"><FolderCheck size={18}/><div><strong>Saved: {history.find(r=>r.parcel_id===p.parcel_id).status.replaceAll('_',' ')}</strong><p>{history.find(r=>r.parcel_id===p.parcel_id).note}</p></div></div>}<form onSubmit={e=>{e.preventDefault();act(()=>mutation('/reviews',{parcel_id:p.parcel_id,run_id:workspace.summary.run_id,status,note},role),'Review saved. Decision history is available in Audit timeline.');}}><label className="s-field">Review outcome<select value={status} onChange={e=>setStatus(e.target.value)}><option value="field_check">Request field verification</option><option value="investigating">Under investigation</option><option value="accepted">Accept with recorded reasoning</option><option value="rejected">Reject proposed association</option></select></label><label className="s-field">Reasoning / field instructions<textarea required minLength={5} maxLength={3000} rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record what the evidence shows and what should happen next…"/></label><div className="case-form-footer"><span>Actor: {role} · local demo persona</span><button className="s-button accent" disabled={busy||role==='viewer'}><ShieldCheck size={14}/>Save review decision</button></div></form></>:<Loading label="Waiting for harmonization results"/>}</section></div>}
 {tab==='documents'&&<section className="s-panel"><div className="panel-heading"><div><Kicker>CONTENT INTEGRITY / SHA-256</Kicker><h2>Evidence vault</h2><p className="s-muted">Uploads are associated with {p?.parcel_id||'the workspace'}.</p></div><input ref={file} type="file" hidden accept=".pdf,.png,.jpg,.jpeg,.txt,.csv,.json,.geojson" onChange={upload}/><button className="s-button accent" disabled={busy||role==='viewer'} onClick={()=>file.current.click()}><Upload size={15}/>Attach evidence</button></div>{docs.data?.length?<div className="document-list">{docs.data.map(d=><article key={d.id}><div className="document-icon"><FileText/></div><div className="document-info"><h3>{d.filename}</h3><p>{d.parcel_id} · {num(d.bytes/1024,1)} KB · {new Date(d.created_at).toLocaleString()}</p><code title={d.sha256}>SHA-256 {d.sha256}</code>{verified[d.id]&&<small className={verified[d.id].intact?'verified':'s-error'}>{verified[d.id].intact?'Byte integrity verified':'Integrity mismatch detected'} · does not establish legal authenticity</small>}</div><div className="document-actions"><button className="s-button" onClick={()=>act(async()=>{const v=await request(`/documents/${d.id}/verify`);setVerified(x=>({...x,[d.id]:v}));},'Integrity check completed.')}><ShieldCheck size={14}/>Verify</button><a className="map-square" href={`${API}/documents/${d.id}/download`} aria-label={`Download ${d.filename}`}><Download size={15}/></a><button className="map-square danger" aria-label={`Delete ${d.filename}`} disabled={busy||role==='viewer'} onClick={()=>act(()=>request(`/documents/${d.id}`,{method:'DELETE',headers:{'X-Workspace-Role':role}}),'Document removed; deletion retained in audit history.')}><Trash2 size={14}/></button></div></article>)}</div>:<div className="vault-empty"><FileText/><h3>Start with a piece of evidence.</h3><p>Attach a survey note, scanned record or exported GeoJSON. Its hash is calculated locally and retained with the file.</p><small>PDF, images, TXT, CSV, JSON · up to 15 MB</small></div>}</section>}
 {tab==='audit'&&<section className="s-panel"><div className="panel-heading"><div><Kicker>APPEND-ONLY EVENT HISTORY / LOCAL DATABASE</Kicker><h2>Every action leaves a trail.</h2></div><History/></div><div className="audit-list">{audit.data?.length?audit.data.map(e=><article key={e.id}><div className="audit-dot"/><div><strong>{e.action.replaceAll('.',' / ').replaceAll('_',' ')}</strong><p>{e.target}</p><small>{e.actor} · {new Date(e.at).toLocaleString()}</small><details><summary>Event details</summary><pre>{JSON.stringify(JSON.parse(e.detail),null,2)}</pre></details></div></article>):<p className="s-muted">Save a review, upload evidence or create a field task to begin the audit history.</p>}</div></section>}
 <SourceNote>Prototype role selection is a local demonstration, not production authentication. Reviews are scoped to a harmonization run. Document hashes check byte integrity, not ownership or legal validity.</SourceNote></div>;
}
