import {lazy,Suspense,useRef,useState} from 'react';
import {Search,Maximize,Layers3,Box,Download,ArrowUpRight,MapPin,ChartNoAxesCombined} from 'lucide-react';
import {useResource,Loading,Kicker,num,downloadJSON} from '../features/intelligence/shared';
import {CLUSTER_COLORS} from '../features/intelligence/GeoCanvas';
const GeoCanvas=lazy(()=>import('../features/intelligence/GeoCanvas'));
export default function CityAtlas(){
 const wards=useResource('/city/wards'),ins=useResource('/city/insights'),map=useRef();
 const [mode,setMode]=useState('value'),[threeD,setThreeD]=useState(true),[base,setBase]=useState('dark'),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[cluster,setCluster]=useState('all'),[tab,setTab]=useState('rankings'),[order,setOrder]=useState('high');
 if(!wards.data||!ins.data)return <Loading error={wards.error||ins.error} retry={()=>{wards.refresh();ins.refresh();}}/>;
 const data=ins.data,filtered={...wards.data,features:wards.data.features.filter(f=>cluster==='all'||String(f.properties.cluster)===cluster)};
 const choose=p=>{setSelected(p);map.current?.fly(p.longitude,p.latitude,12.5);};
 const ranking=(order==='high'?data.ranking:[...data.ranking].reverse()).filter(r=>r.name.toLowerCase().includes(query.toLowerCase())||r.ward_no===query).filter(r=>cluster==='all'||String(r.cluster)===cluster);
 return <div className="atlas-page"><div className="atlas-top"><div><Kicker>URBANSCOPE / SPATIAL ANALYTICS</Kicker><h1>Bengaluru, in perspective.</h1></div><div className="atlas-top-stats"><span><strong>243</strong> WARDS</span><span><strong>{data.area_km2}</strong> km²</span><span className="live-label"><i/> REAL GEOMETRY</span></div></div><div className="atlas-body"><div className="atlas-map-wrap"><Suspense fallback={<Loading/>}><GeoCanvas ref={map} wards={filtered} mode={mode} threeD={threeD} basemap={base} selected={selected?.ward_id} onSelect={choose}/></Suspense>
  <div className="map-floating-toolbar"><div className="s-segments">{[['value','Spatial index'],['hotspots','Hotspots'],['clusters','Clusters']].map(([id,name])=><button key={id} className={mode===id?'active':''} onClick={()=>setMode(id)}>{name}</button>)}</div><button className={`map-square ${threeD?'active':''}`} title="Toggle 3D" aria-label="Toggle 3D" onClick={()=>setThreeD(!threeD)}><Box size={17}/></button><button className="map-square" title="Reset city view" aria-label="Reset city view" onClick={()=>map.current?.reset()}><Maximize size={16}/></button></div>
  <div className="atlas-floating-info"><span>BENGALURU METROPOLITAN AREA</span><h2>{mode==='hotspots'?'Where patterns concentrate.':mode==='clusters'?'Four urban signatures.':'The shape of urban value.'}</h2><p>{mode==='hotspots'?`${data.hotspots} hotspots · ${data.coldspots} coldspots / exploratory Gi*`:mode==='clusters'?'Deterministic k-means / five spatial indicators':'Height exaggerates a calculated proxy, not ground elevation'}</p></div>
  <div className="atlas-legend">{mode==='clusters'?data.clusters.map(c=><span key={c.id}><i style={{background:CLUSTER_COLORS[c.id]}}/>{c.name}</span>):mode==='hotspots'?<><span><i style={{background:'#f29872'}}/>Hotspot</span><span><i style={{background:'#6da5ef'}}/>Coldspot</span><span><i style={{background:'#527479'}}/>Not significant</span></>:<><span>Lower index</span><div className="color-ramp"/><span>Higher index</span></>}</div>
  <div className="basemap-switch">{['dark','light','satellite','none'].map(b=><button key={b} aria-pressed={base===b} className={base===b?'active':''} onClick={()=>setBase(b)}>{b==='none'?'Offline':b}</button>)}</div>
 </div><aside className="atlas-inspector"><div className="atlas-inspector-head"><Layers3 size={18}/><strong>Spatial intelligence</strong><span>01—243</span></div><div className="atlas-inspector-scroll">
 {selected?<div className="ward-selected"><Kicker>WARD {selected.ward_no} / SELECTED</Kicker><h2>{selected.name}</h2><span className="s-badge">{selected.cluster_name}</span><div className="ward-values"><div><small>AREA</small><strong>{num(selected.area_km2,2)}<em>km²</em></strong></div><div><small>CENTRE DISTANCE</small><strong>{num(selected.distance_km,1)}<em>km</em></strong></div><div><small>RELATIVE TO MEDIAN</small><strong>{selected.deviation>0?'+':''}{num(selected.deviation*100,1)}<em>%</em></strong></div><div><small>LOCAL Gi* Z</small><strong>{num(selected.gi_z,2)}</strong></div></div><button className="text-action" onClick={()=>setSelected(null)}>Clear selection</button></div>:<div className="ward-intro"><MapPin/><h3>A city is more than its boundaries.</h3><p>Select a ward to inspect its area, accessibility, cluster and spatial context.</p></div>}
 <div className="inspector-tabs s-tabs">{['rankings','patterns','method'].map(t=><button key={t} className={tab===t?'is-active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='rankings'&&<><label className="s-search"><Search size={14}/><input aria-label="Search wards" placeholder="Find a ward or number…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="atlas-filters"><select aria-label="Cluster filter" value={cluster} onChange={e=>setCluster(e.target.value)}><option value="all">All clusters</option>{data.clusters.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select aria-label="Ranking order" value={order} onChange={e=>setOrder(e.target.value)}><option value="high">Highest first</option><option value="low">Lowest first</option></select></div><div className="ward-rankings">{ranking.slice(0,30).map((r,i)=><button key={r.ward_id} onClick={()=>choose(r)} className={selected?.ward_id===r.ward_id?'active':''}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{r.name}</strong><small>Ward {r.ward_no} · {num(r.area_km2,2)} km²</small><i style={{width:`${r.value_proxy/160000*100}%`,background:CLUSTER_COLORS[r.cluster]}}/></div><em>{r.deviation>0?'+':''}{num(r.deviation*100)}%</em></button>)}{!ranking.length&&<p className="s-muted">No matching ward.</p>}</div><p className="s-small">Showing {Math.min(30,ranking.length)} of {ranking.length}. Values are deviation from the median proxy, not observed growth.</p></>}
 {tab==='patterns'&&<div className="patterns-panel"><h3>Distance × spatial proxy</h3><svg viewBox="0 0 280 165" role="img" aria-label="Ward distance and proxy scatter plot"><line x1="25" y1="140" x2="270" y2="140" stroke="#a2b7bd"/><line x1="25" y1="10" x2="25" y2="140" stroke="#a2b7bd"/>{data.ranking.map(r=><circle key={r.ward_id} cx={25+r.distance_km/30*240} cy={140-r.value_proxy/160000*130} r="2.3" fill={CLUSTER_COLORS[r.cluster]} opacity=".7"/>)}<text x="90" y="159">Distance to centre (km)</text></svg><div className="pattern-numbers"><span>R²<strong>{data.regression.r2.toFixed(3)}</strong></span><span>Correlation<strong>{data.regression.correlation.toFixed(3)}</strong></span></div><h3>Distribution of the proxy</h3><svg viewBox="0 0 280 165" role="img" aria-label="Lorenz curve of ward spatial proxy"><line x1="25" y1="140" x2="260" y2="10" stroke="#748b93" strokeDasharray="4 4"/><polyline points={data.lorenz.map((v,i)=>`${25+i/(data.lorenz.length-1)*235},${140-v*130}`).join(' ')} stroke="#66aa90" strokeWidth="3" fill="none"/><text x="77" y="159">Cumulative ward share</text></svg><div className="pattern-numbers"><span>Gini<strong>{data.gini}</strong></span><span>Top 10% share<strong>{num(data.top_decile_share*100,1)}%</strong></span></div><p className="s-small">This describes a modeled spatial index, not household wealth or verified land prices. Distance is already a factor in this index; the correlation is not independent evidence.</p></div>}
 {tab==='method'&&<div className="method-panel"><h3>Inspectable by design.</h3><p>{data.provenance.metric}.</p><ol><li>Compute geodesic context and projected ward area.</li><li>Build UrbanScope's area/accessibility index.</li><li>Standardize five indicators; cluster into four groups.</li><li>Evaluate local Gi* with eight nearest neighbours and self.</li></ol><p>{data.provenance.significance}.</p><p>{data.provenance.snapshot_note}.</p><a href={data.provenance.url} target="_blank" rel="noreferrer">DataMeet source <ArrowUpRight size={13}/></a><button className="s-button" onClick={()=>downloadJSON('bengaluru-ward-analysis.geojson',wards.data)}><Download size={14}/>Export ward analysis</button></div>}
 </div></aside></div></div>;
}
