import {useState} from 'react';
import {Search,ArrowUpRight} from 'lucide-react';
import SectionHeader from '../components/SectionHeader';
import StatusIndicator from '../components/StatusIndicator';
import EmptyState from '../components/EmptyState';
import {titleCase,percent,metricEvidence} from '../api/presentation';
export default function Conflicts({workspace,onInspect}) {
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('ALL'),[kind,setKind]=useState('ALL');
 const {conflicts,changes}=workspace;
 const matches=(c,f)=>f==='ALL'||(f==='UNASSIGNED'?!c.parcel_id:c.severity===(f==='REVIEW'?'WARNING':f));
 const rows=conflicts.filter(c=>matches(c,filter)&&(kind==='ALL'||c.type===kind)&&`${c.parcel_id||''} ${c.type} ${c.description} ${JSON.stringify(c.metrics)}`.toLowerCase().includes(query.toLowerCase()));
 return <><SectionHeader title="Conflict register" description={`${conflicts.length} measured issues · recommendations require human review`}/><div className="registry-toolbar"><div className="segmented">{['ALL','CRITICAL','REVIEW','UNASSIGNED'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'is-active':''} onClick={()=>setFilter(f)}>{titleCase(f)} <span>{conflicts.filter(c=>matches(c,f)).length}</span></button>)}</div><label className="search-field"><Search/><input aria-label="Search conflicts" placeholder="Search parcel or evidence" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Conflict type" value={kind} onChange={e=>setKind(e.target.value)}><option value="ALL">All issue types</option>{[...new Set(conflicts.map(c=>c.type))].map(t=><option key={t} value={t}>{titleCase(t)}</option>)}</select></div><div className="table-wrap"><table className="data-table conflict-table"><thead><tr>{['Parcel / observation','Issue','Severity','Confidence','Evidence & recommendation',''].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map(c=><tr key={c.id} className={c.parcel_id?'clickable':''} tabIndex={c.parcel_id?0:undefined} onClick={()=>c.parcel_id&&onInspect(c.parcel_id)} onKeyDown={e=>e.key==='Enter'&&c.parcel_id&&onInspect(c.parcel_id)}><td><code>{c.parcel_id||c.metrics?.source_id||'Unassigned'}</code><small>{c.sources?.join(', ')}</small></td><td>{titleCase(c.type)}</td><td><StatusIndicator status={c.severity}/></td><td className="numeric">{percent(c.confidence)}</td><td>{c.description}<small className="evidence-metrics">{metricEvidence(c.metrics)}</small><small>{c.recommended_action}</small></td><td>{c.parcel_id&&<ArrowUpRight size={14}/>}</td></tr>)}</tbody></table>{!rows.length&&<EmptyState title="No matching issues" description="Adjust the search or severity filter."/>}</div><div className="table-footer">{rows.length} of {conflicts.length} issues · Select an assigned record to inspect map evidence</div><SectionHeader title="Detected differences" description={`${changes.length} changes and source disagreements`}/><div className="table-wrap"><table className="data-table"><thead><tr><th>Parcel</th><th>Difference</th><th>Observation evidence</th></tr></thead><tbody>{changes.map(c=><tr key={c.id} tabIndex={c.parcel_id?0:undefined} className={c.parcel_id?'clickable':''} onClick={()=>c.parcel_id&&onInspect(c.parcel_id)} onKeyDown={e=>e.key==='Enter'&&c.parcel_id&&onInspect(c.parcel_id)}><td><code>{c.parcel_id||'Unassigned'}</code></td><td>{titleCase(c.type)}</td><td>{c.description}<small>{metricEvidence(c.metrics||{iou:c.iou,area_difference_percent:c.area_difference_percent})}</small></td></tr>)}</tbody></table></div></>;
}

