import {Download,FileText,ShieldCheck} from 'lucide-react';
import {API} from '../api/client';
import {formatNumber} from '../api/presentation';
import SectionHeader from '../components/SectionHeader';
export default function Export({workspace}) {
 const {summary}=workspace;
 const files=[['harmonized.geojson','harmonized_parcels.geojson','GeoJSON',summary?.harmonized_parcels,'Master geometry and parcel evidence'],['conflicts.csv','conflicts.csv','CSV',summary?.conflicts,'Conflict and review measurements'],['changes.csv','change_report.csv','CSV',summary?.changes,'Building changes and boundary disagreements'],['summary.json','run_summary.json','JSON',null,'Computed metrics, warnings and run stages']];
 return <><SectionHeader title="Export artifacts" description="Reproducible outputs from the latest completed run"/><div className="table-wrap"><table className="data-table"><thead><tr><th>Artifact</th><th>Format</th><th>Records</th><th>Run</th><th/></tr></thead><tbody>{files.map(([route,name,format,count,desc])=><tr key={route}><td><code>{name}</code><small>{desc}</small></td><td>{format}</td><td className="numeric">{count==null?'—':formatNumber(count)}</td><td><code>{summary?.run_id||'Run required'}</code></td><td>{summary?<a className="button quiet" href={`${API}/export/${route}`} download><Download/>Download</a>:<span className="muted">Unavailable</span>}</td></tr>)}</tbody></table></div><div className="integrated-export-actions"><a className="s-button accent" href={API+'/evidence-bundle'} download><ShieldCheck size={15}/>Complete evidence bundle</a>{summary&&<a className="s-button" href={API+'/report'} target="_blank" rel="noreferrer"><FileText size={15}/>Print-ready evidence report</a>}<span>Core outputs + reviewer decisions + document hashes + operations history</span></div><section className="export-metadata technical-section"><h3>Run metadata</h3><dl className="detail-fields">{[['Run identifier',summary?.run_id],['Display geometry','EPSG:4326 / WGS84'],['Analysis CRS',summary?.analysis_crs],['Processing duration',summary?`${formatNumber(summary.duration_ms)} ms`:'—'],['Data mode',workspace.demo?'Synthetic local demo':'User provided / unverified'],['Master geometry policy','Cadastral boundary retained pending survey review']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'—'}</dd></div>)}</dl><p className="muted">These artifacts provide computed evidence. Demo fixtures do not represent official land ownership.</p></section></>;
}
