import SectionHeader from '../components/SectionHeader';
import RunProgress from '../components/RunProgress';
import StatusIndicator from '../components/StatusIndicator';
import {formatNumber,percent} from '../api/presentation';
export default function Harmonization({workspace,onNavigate}) {
 const {status,summary,parcels,datasets}=workspace;
 const rows=[['Observation roles',datasets.length],['Input features',summary?.input_features],['Master parcels',summary?.harmonized_parcels],['Matched',summary?.matched],['Needs review',summary?.needs_review],['Parcels with repairs',summary?parcels.filter(p=>p.metadata?.repair_operations?.length).length:null],['Conflict records',summary?.conflicts],['Detected differences',summary?.changes],['Mean confidence',summary?percent(summary.average_confidence):'—'],['Analysis CRS',summary?.analysis_crs||'EPSG:32643']];
 return <><SectionHeader title="Harmonization pipeline" description="Local, explainable processing · actual stage status and measured timings"/><div className="run-context"><StatusIndicator status={status.status}/><code>{status.run_id||summary?.run_id||'No completed run'}</code><span>{status.cached?'Cached result':'Local processing'}</span><span className="push-right">{summary?`${formatNumber(summary.duration_ms)} ms total`:'Awaiting run'}</span></div><div className="pipeline-progress"><span style={{width:`${status.progress||0}%`}}/></div><div className="pipeline-layout"><section><RunProgress status={status}/><div className="method-note"><strong>Matching method</strong><p>Polygon overlap, centroid proximity, area ratio, boundary similarity and normalized attributes contribute measured evidence. Conflicts force human review. Cadastral geometry remains the master boundary.</p></div></section><aside className="processing-summary"><h3>Latest completed snapshot</h3><dl className="detail-fields">{rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{typeof v==='number'?formatNumber(v):v??'—'}</dd></div>)}</dl><button className="button primary" disabled={!summary} onClick={()=>onNavigate('Map Review')}>Inspect master layer</button><p className="muted">{summary?.run_id||'Run harmonization to generate a snapshot.'}</p></aside></div>{summary?.warnings?.length>0&&<details className="technical-section"><summary>Input warnings ({summary.warnings.length})</summary><ul>{summary.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>}</>;
}
