import {useState} from 'react';
import {ArrowUpRight,X} from 'lucide-react';
import SectionHeader from '../components/SectionHeader';
import StatusIndicator from '../components/StatusIndicator';
import UploadForm from '../features/datasets/UploadForm';
import ImportedSources from '../features/intelligence/ImportedSources';
import {datasetLabel,formatNumber,percent,titleCase,sourceName} from '../api/presentation';
export default function Sources({workspace,role,onNavigate}) {
 const [selected,setSelected]=useState('municipal');
 const {datasets,demo}=workspace, d=datasets.find(d=>d.id===selected);
 return <><SectionHeader title="Source registry" description={`${datasets.length} observation roles · measured metadata and explicit field mappings`}/><div className={`registry-layout ${d?'has-detail':''}`}><div className="table-wrap"><table className="data-table"><thead><tr>{['Dataset','Format','Geometry','Source CRS','Features','Valid','Quality','Status',''].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{datasets.map(item=><tr key={item.id} tabIndex={0} className={`clickable ${selected===item.id?'selected-row':''}`} onClick={()=>setSelected(item.id)} onKeyDown={e=>e.key==='Enter'&&setSelected(item.id)}><td><strong>{sourceName(item.id)}</strong><small>{item.id}</small></td><td>{item.format}</td><td>{item.geometry_types?.join(', ')||(item.id==='revenue'?'Records':'Unavailable')}</td><td className="mono">{item.crs||'—'}</td><td className="numeric">{formatNumber(item.feature_count)}</td><td className="numeric">{item.crs?formatNumber(item.valid_geometry_count):'—'}</td><td className="numeric">{item.quality_indicator==null?'—':percent(item.quality_indicator,0)}</td><td><StatusIndicator status={item.status}/></td><td><ArrowUpRight size={14}/></td></tr>)}</tbody></table><div className="table-footer">Select a dataset to inspect mappings, quality warnings and CRS handling.</div></div>{d&&<aside className="registry-detail"><div className="detail-heading"><h3>{sourceName(d.id)}</h3><button className="icon-button" aria-label="Close source details" onClick={()=>setSelected('')}><X/></button></div><dl className="detail-fields">{[['Source CRS',d.crs||(d.id==='revenue'?'Non-spatial records':'Not available')],['Analysis CRS',workspace.summary?.analysis_crs||'Not determined'],['Features',formatNumber(d.feature_count)],['Data label',d.data_label||'Source data']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{k==='Data label'?datasetLabel(v):v}</dd></div>)}</dl><h4>Applied field mappings</h4><table className="data-table mapping-table"><thead><tr><th>Source field</th><th>Canonical</th></tr></thead><tbody>{Object.entries(d.field_mapping||{}).map(([k,v])=><tr key={k}><td><code>{k}</code></td><td>{titleCase(String(v))}</td></tr>)}</tbody></table><h4>Quality warnings</h4>{d.warnings?.length?<ul className="evidence-list">{d.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul>:<p className="muted">No source warnings reported.</p>}<details><summary>Unapplied mapping suggestions</summary><pre>{JSON.stringify(d.mapping_suggestions||{},null,2)}</pre></details></aside>}</div>{!demo&&role!=='viewer'&&<section className="technical-section"><h3>Ingest source observation</h3><UploadForm workspace={workspace}/></section>}<ImportedSources onNavigate={onNavigate}/></>;
}

