import {lazy,Suspense,useRef,useState} from 'react';
import {ScanLine,Trees,Layers,Upload,Maximize,Download,Ruler,X,Check,Image,Mountain} from 'lucide-react';
import {useResource,Loading,Kicker,num,downloadJSON,SourceNote} from '../features/intelligence/shared';
import {request} from '../api/client';
import SurveyHistory from '../features/intelligence/SurveyHistory';
const GeoCanvas=lazy(()=>import('../features/intelligence/GeoCanvas'));
function distance(a,b){const r=Math.PI/180;const dlat=(b[1]-a[1])*r,dlon=(b[0]-a[0])*r;return 6371000*2*Math.asin(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(a[1]*r)*Math.cos(b[1]*r)*Math.sin(dlon/2)**2));}
export default function SurveyLab({role='officer'}){
 const survey=useResource('/survey'),rasters=useResource('/survey/rasters'),map=useRef(),file=useRef();
 const [comparison,setComparison]=useState(null);
 const [overlay,setOverlay]=useState('ortho'),[canopies,setCanopies]=useState(false),[base,setBase]=useState('satellite'),[raster,setRaster]=useState(null),[uploadRole,setUploadRole]=useState('ndvi'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[measure,setMeasure]=useState(false),[points,setPoints]=useState([]),[tab,setTab]=useState('analysis');
 const d=survey.data;
 async function upload(e){if(!e.target.files[0])return;setBusy(true);setError('');const form=new FormData();form.append('file',e.target.files[0]);form.append('role',uploadRole);try{const r=await request('/survey/rasters',{method:'POST',headers:{'X-Workspace-Role':role},body:form});setRaster(r);await rasters.refresh();}catch(e){setError(e.message);}finally{setBusy(false);e.target.value='';}}
 if(!d)return <Loading error={survey.error} retry={survey.refresh}/>;
 const length=points.reduce((s,p,i)=>i?s+distance(points[i-1],p):s,0);
 const measured=points.length>1?{type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:points}}]}:null;
 return <div className="atlas-page survey-page"><div className="atlas-top"><div><Kicker>LANDROID × KV / IMAGERY INTELLIGENCE</Kicker><h1>See what the ground reveals.</h1></div><div className="atlas-top-stats"><span><strong>{d.area_acres}</strong> ACRES</span><span><strong>{d.coverage_percent}%</strong> IMAGE COVERAGE</span><span className="live-label"><i/> LOCAL ORTHOMOSAIC</span></div></div><div className="atlas-body"><div className="atlas-map-wrap"><Suspense fallback={<Loading/>}><GeoCanvas ref={map} survey={d} threeD={false} basemap={base} overlay={overlay} canopies={canopies} raster={comparison||raster} fence={measured} point={points.at(-1)} onPoint={measure?({lng,lat})=>setPoints(p=>[...p,[lng,lat]]):undefined}/></Suspense><div className="map-floating-toolbar"><div className="s-segments">{[['ortho','Orthomosaic'],['zones','Vegetation zones'],['vegetation','Green cover']].map(([v,t])=><button key={v} className={overlay===v&&!raster?'active':''} onClick={()=>{setOverlay(v);setRaster(null);setComparison(null);}}>{t}</button>)}</div><button className={`map-square ${canopies?'active':''}`} onClick={()=>setCanopies(!canopies)} aria-label="Toggle canopy candidates" title="Canopy candidates"><Trees size={17}/></button><button className={`map-square ${measure?'active':''}`} onClick={()=>{setMeasure(!measure);setPoints([]);}} aria-label="Measure distance" title="Measure distance"><Ruler size={17}/></button><button className="map-square" onClick={()=>map.current?.reset()} aria-label="Reset survey view"><Maximize size={16}/></button></div>
 <div className="survey-map-label"><span>FIELD SURVEY / 001</span><h2>Kallapuram</h2><p>10.4295° N · 77.3043° E</p><small>EPSG:32643 → WGS84 / actual imported survey boundary</small></div>
 {measure&&<div className="measurement-readout"><Ruler size={16}/><div><strong>{num(length,1)} m</strong><small>{points.length} vertices · click map to measure</small></div><button onClick={()=>setPoints([])}>Clear</button><button aria-label="Stop measuring" onClick={()=>setMeasure(false)}><X size={14}/></button></div>}
 <div className="basemap-switch">{['satellite','dark','none'].map(b=><button key={b} className={base===b?'active':''} onClick={()=>setBase(b)}>{b==='none'?'Offline':b}</button>)}</div><div className="survey-caption">RGB imagery · capture date unavailable · canopy candidates require field validation</div></div>
 <aside className="atlas-inspector"><div className="atlas-inspector-head"><ScanLine size={18}/><strong>Survey diagnostics</strong><span>LOCAL</span></div><div className="atlas-inspector-scroll"><div className="survey-score"><span>VEGETATION COVER / OBSERVED IMAGE</span><strong>{d.vegetation_percent}<small>%</small></strong><div className="survey-score-bar"><i style={{width:`${d.vegetation_percent}%`}}/></div><p>RGB threshold mask within the covered portion of the boundary.</p></div><div className="inspector-tabs s-tabs">{['analysis','rasters','history','method'].map(t=><button key={t} className={tab===t?'is-active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='analysis'&&<div className="survey-analysis"><h3>Land-cover signature</h3><div className="zone-stack">{d.zones.map(z=><i key={z.name} style={{width:`${z.percent}%`,background:z.color}} title={`${z.name}: ${z.percent}%`}/>)}</div>{d.zones.map(z=><div className="zone-row" key={z.name}><i style={{background:z.color}}/><span>{z.name}</span><strong>{z.percent}%</strong></div>)}<div className="survey-metrics"><div><Trees/><strong>{d.canopy_count}</strong><span>Candidate crowns</span></div><div><ScanLine/><strong>{d.small_canopies}</strong><span>Small-crown outliers</span></div></div><dl className="s-definition"><div><dt>Boundary area</dt><dd>{num(d.area_sqm,1)} m²</dd></div><div><dt>Boundary perimeter</dt><dd>{num(d.perimeter_m,1)} m</dd></div><div><dt>Approx. pixel size</dt><dd>{d.gsd_m} m</dd></div><div><dt>Image coverage</dt><dd>{d.coverage_percent}% of boundary</dd></div><div><dt>Mean RGB greenness</dt><dd>{d.mean_gcc}</dd></div></dl><button className="s-button full" onClick={()=>downloadJSON('survey-canopy-candidates.geojson',d.canopies)}><Download size={14}/>Export canopy candidates</button><SourceNote>These are image-derived candidates, not a verified tree census. RGB greenness is not multispectral NDVI.</SourceNote></div>}
 {tab==='rasters'&&<div className="survey-analysis"><h3>Bring your own survey</h3><p className="s-muted">Upload a calibrated, georeferenced GeoTIFF. Reprojection and a preview are generated locally.</p><label className="s-field">Raster interpretation<select value={uploadRole} onChange={e=>setUploadRole(e.target.value)}><option value="ndvi">NDVI (−1 to 1)</option><option value="dem">Elevation / DEM</option><option value="ortho">RGB orthomosaic</option></select></label><input ref={file} hidden type="file" accept=".tif,.tiff" onChange={upload}/><button className="s-button accent full" disabled={busy||role==='viewer'} onClick={()=>file.current.click()}><Upload size={14}/>{busy?'Processing raster…':'Upload GeoTIFF'}</button><small className="s-small">40 MB maximum · embedded CRS required</small>{error&&<p className="s-error" role="alert">{error}</p>}<div className="raster-list">{rasters.data?.map(r=><button key={r.id} className={raster?.id===r.id?'active':''} onClick={()=>{setRaster(r);setComparison(null);}}><Layers size={15}/><div><strong>{r.filename}</strong><small>{r.role.toUpperCase()} · {r.source_crs}</small></div></button>)}</div>{raster&&<><h3>{raster.role.toUpperCase()} statistics</h3><dl className="s-definition">{Object.entries(raster.stats).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{raster.zones.map(z=><div key={z.name} className="zone-row"><i style={{background:z.color}}/><span>{z.name}</span><strong>{z.percent}%</strong></div>)}<p className="s-small">{raster.note}</p><button className="text-action" onClick={()=>{setRaster(null);map.current?.reset();}}>Return to local survey</button></>}</div>}
 {tab==='history'&&<SurveyHistory rasters={rasters.data} role={role} onCompare={setComparison}/>}
 {tab==='method'&&<div className="method-panel"><h3>Pixels into evidence.</h3><ol><li>Reproject the source boundary from UTM 43N into WGS84.</li><li>Mosaic the two available highest-resolution imagery tiles.</li><li>Clip analysis to the visible boundary and report partial coverage.</li><li>Compute green chromatic coordinate and threshold vegetation.</li><li>Separate candidate crowns using distance peaks and watershed.</li></ol><p>{d.provenance.limitations}</p><p>{d.provenance.imagery}.</p><button className="s-button" onClick={()=>downloadJSON('kallapuram-survey-summary.json',d)}><Download size={14}/>Export survey evidence</button></div>}
 </div></aside></div></div>;
}
