import {useEffect,useState} from 'react';
import {LoaderCircle,RefreshCw,ArrowUpRight} from 'lucide-react';
import {request,API} from '../../api/client';
export function useResource(path){const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);async function refresh(){setLoading(true);setError('');try{setData(await request(path));}catch(e){setError(e.message);}finally{setLoading(false);}}useEffect(()=>{let live=true;setLoading(true);request(path).then(d=>live&&setData(d)).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false;};},[path]);return {data,error,loading,refresh,setData};}
export function Loading({error,retry,label='Preparing spatial workspace'}){return <div className="studio-loading">{error?<><strong>Could not load this workspace</strong><p>{error}</p>{retry&&<button className="s-button" onClick={retry}><RefreshCw size={14}/>Try again</button>}</>:<><LoaderCircle className="spin"/><p>{label}</p></>}</div>;}
export function Kicker({children}){return <div className="s-kicker"><i/>{children}</div>;}
export function Heading({eyebrow,title,description,children}){return <header className="s-heading"><div><Kicker>{eyebrow}</Kicker><h1>{title}</h1><p>{description}</p></div><div className="s-heading-actions">{children}</div></header>;}
export function Metric({label,value,unit,detail,color}){return <div className="s-metric"><span>{label}</span><strong style={{color}}>{value}<small>{unit}</small></strong>{detail&&<p>{detail}</p>}</div>;}
export function SourceNote({children}){return <div className="source-note"><span>PROVENANCE</span><p>{children}</p></div>;}
export function MiniLine({values=[],color='#8fdcb5',height=120,label='Trend'}){const clean=values.map(v=>Number(v)||0);const max=Math.max(...clean,1),min=Math.min(...clean,0),points=clean.map((v,i)=>`${i/Math.max(1,clean.length-1)*400},${height-10-(v-min)/(max-min||1)*(height-25)}`).join(' ');return <svg className="mini-line" viewBox={`0 0 400 ${height}`} role="img" aria-label={label} preserveAspectRatio="none"><defs><linearGradient id={`fade${color.replace('#','')}`} x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".24"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient></defs>{[.25,.5,.75].map(y=><line key={y} x1="0" x2="400" y1={y*height} y2={y*height} stroke="currentColor" opacity=".1"/>)}<polygon points={`0,${height} ${points} 400,${height}`} fill={`url(#fade${color.replace('#','')})`}/><polyline points={points} fill="none" stroke={color} strokeWidth="2.5" vectorEffect="non-scaling-stroke"/></svg>;}
export function Action({children,onClick,primary=false,...rest}){return <button className={`s-button ${primary?'accent':''}`} onClick={onClick} {...rest}>{children}</button>;}
export function LinkAction({children,href}){return <a className="s-button" href={`${API}${href}`} download>{children}<ArrowUpRight size={14}/></a>;}
export const num=(v,d=0)=>Number(v??0).toLocaleString('en-IN',{maximumFractionDigits:d});
export function mutation(path,body,role='officer',method='POST'){return request(path,{method,headers:{'Content-Type':'application/json','X-Workspace-Role':role},body:JSON.stringify(body)});}
export function downloadJSON(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
